# frozen_string_literal: true

class Event < Sequel::Model
  many_to_one :user
  many_to_one :troop
end

# Table: events
# Columns:
#  id          | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  user_id     | integer                     | NOT NULL
#  troop_id    | integer                     | NOT NULL
#  name        | text                        | NOT NULL
#  description | text                        | NOT NULL
#  starts_at   | timestamp without time zone | NOT NULL
#  ends_at     | timestamp without time zone | NOT NULL
#  created_at  | timestamp without time zone | NOT NULL DEFAULT CURRENT_TIMESTAMP
#  updated_at  | timestamp without time zone | NOT NULL DEFAULT CURRENT_TIMESTAMP
# Indexes:
#  events_pkey | PRIMARY KEY btree (id)
# Foreign key constraints:
#  events_troop_id_fkey | (troop_id) REFERENCES troops(id) ON DELETE CASCADE
#  events_user_id_fkey  | (user_id) REFERENCES users(id) ON DELETE CASCADE
