# frozen_string_literal: true

class User < Sequel::Model
  one_to_many :memberships
  one_to_many :troops, through: :memberships
  one_to_many :events
end

# Table: users
# Columns:
#  id         | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name       | text                        | NOT NULL
#  email      | text                        | NOT NULL
#  password   | text                        | NOT NULL
#  admin      | boolean                     | NOT NULL DEFAULT false
#  created_at | timestamp without time zone | NOT NULL DEFAULT CURRENT_TIMESTAMP
#  updated_at | timestamp without time zone | NOT NULL DEFAULT CURRENT_TIMESTAMP
#  deleted_at | timestamp without time zone | NOT NULL DEFAULT CURRENT_TIMESTAMP
# Indexes:
#  users_pkey | PRIMARY KEY btree (id)
# Referenced By:
#  events      | events_user_id_fkey      | (user_id) REFERENCES users(id) ON DELETE CASCADE
#  memberships | memberships_user_id_fkey | (user_id) REFERENCES users(id) ON DELETE CASCADE
